version: "3.9"

services:
  # image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: mysql:8.0.43
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3305:3306"
    networks:
      - laravel

  # redis
  redis:
    image: redis:latest
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - "1026:1025"  # porta SMTP
      - "8025:8025"  # painel web
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
